server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/productmanager
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
