version: '3'

services:
  mysql-db:
    image: mysql:latest
    container_name: my-mysql-container-productmanager
    environment:
#      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: productmanager
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
